##
# Extensions to the TagQueryGrammar module, generated by Treetop. The classes
# contained in this module are applied to the nodes of the parsed syntax tree
# for easier interpretation later.
#
# @see http://treetop.rubyforge.org/
#
# @author Josh Lindsey
# @since 2.3.0
module TagQueryGrammar
  class Tag < Treetop::Runtime::SyntaxNode; end

  class Whitespace < Treetop::Runtime::SyntaxNode; end

  class QueryGroup < Treetop::Runtime::SyntaxNode; end

  class GroupStart < Treetop::Runtime::SyntaxNode; end

  class GroupEnd < Treetop::Runtime::SyntaxNode; end

  class AndLiteral < Treetop::Runtime::SyntaxNode; end

  class OrLiteral < Treetop::Runtime::SyntaxNode; end
end
